name: Ubuntu Runner

on:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest

    steps:
      - name: System info
        run: |
          echo "CPU:"
          nproc
          echo "RAM:"
          free -h
          echo "Disk:"
          df -h

      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          
