name: Ubuntu Runner

on:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest

    steps:
      - name: System info
        run: |
          echo "CPU:"
          nproc
          echo "RAM:"
          free -h
          echo "Disk:"
          df -h
          echo "OS:"
          cat /etc/os-release
